import 'bloc/message_open_bloc.dart';import 'models/message_open_model.dart';import 'package:arone_jerome_s_application1/core/app_export.dart';import 'package:arone_jerome_s_application1/widgets/app_bar/appbar_image.dart';import 'package:arone_jerome_s_application1/widgets/app_bar/appbar_image_3.dart';import 'package:arone_jerome_s_application1/widgets/app_bar/appbar_subtitle_1.dart';import 'package:arone_jerome_s_application1/widgets/app_bar/appbar_subtitle_5.dart';import 'package:arone_jerome_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:arone_jerome_s_application1/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class MessageOpenScreen extends StatelessWidget {const MessageOpenScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<MessageOpenBloc>(create: (context) => MessageOpenBloc(MessageOpenState(messageOpenModelObj: MessageOpenModel()))..add(MessageOpenInitialEvent()), child: MessageOpenScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: CustomAppBar(leadingWidth: 51.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleft, margin: EdgeInsets.only(left: 20.h, top: 17.v, bottom: 10.v), onTap: () {onTapArrowleftone(context);}), centerTitle: true, title: Column(children: [AppbarSubtitle1(text: "lbl_chris_evans".tr), AppbarSubtitle5(text: "lbl_active_4h_ago".tr, margin: EdgeInsets.symmetric(horizontal: 18.h))]), actions: [AppbarImage3(svgPath: ImageConstant.imgGroup, margin: EdgeInsets.fromLTRB(20.h, 30.v, 20.h, 23.v))], styleType: Style.bgFill_1), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 23.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 210.h, child: Text("msg_hey_were_you_able2".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumGray700.copyWith(height: 1.32))), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(top: 32.v, right: 4.h), child: Text("msg_yes_i_was_how".tr, style: CustomTextStyles.bodyMediumBluegray400))), Spacer(), BlocSelector<MessageOpenBloc, MessageOpenState, TextEditingController?>(selector: (state) => state.messageController, builder: (context, messageController) {return CustomTextFormField(controller: messageController, hintText: "lbl_send_a_message".tr, hintStyle: CustomTextStyles.labelLargeRobotoGray500, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(21.h, 11.v, 16.h, 11.v), child: CustomImageView(svgPath: ImageConstant.imgCameraaltlight)), prefixConstraints: BoxConstraints(maxHeight: 42.v), suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 9.v, 16.h, 7.v), child: CustomImageView(svgPath: ImageConstant.imgGetstyliniconssendBlack900)), suffixConstraints: BoxConstraints(maxHeight: 42.v), contentPadding: EdgeInsets.symmetric(vertical: 13.v), borderDecoration: TextFormFieldStyleHelper.fillSecondaryContainer, fillColor: theme.colorScheme.secondaryContainer.withOpacity(0.2));})])))); } 


/// Navigates to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is
/// used to build the navigation stack. When the action is triggered, this
/// function uses the [NavigatorService] to navigate to the previous screen
/// in the navigation stack.
onTapArrowleftone(BuildContext context) { NavigatorService.goBack(); } 
 }
