import '../notifications_page/widgets/userconnection_item_widget.dart';import 'bloc/notifications_bloc.dart';import 'models/notifications_model.dart';import 'models/userconnection_item_model.dart';import 'package:arone_jerome_s_application1/core/app_export.dart';import 'package:arone_jerome_s_application1/widgets/app_bar/appbar_image.dart';import 'package:arone_jerome_s_application1/widgets/app_bar/appbar_subtitle_1.dart';import 'package:arone_jerome_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class NotificationsPage extends StatelessWidget {const NotificationsPage({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<NotificationsBloc>(create: (context) => NotificationsBloc(NotificationsState(notificationsModelObj: NotificationsModel()))..add(NotificationsInitialEvent()), child: NotificationsPage()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: CustomAppBar(leadingWidth: 51.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleft, margin: EdgeInsets.only(left: 20.h, top: 17.v, bottom: 10.v), onTap: () {onTapArrowleftone(context);}), centerTitle: true, title: AppbarSubtitle1(text: "lbl_notifications".tr), styleType: Style.bgFill_1), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 9.v), child: Column(children: [Expanded(child: SizedBox(width: double.maxFinite, child: Container(padding: EdgeInsets.symmetric(horizontal: 30.h), decoration: AppDecoration.fillOnPrimaryContainer, child: Column(mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 17.v), Expanded(child: BlocSelector<NotificationsBloc, NotificationsState, NotificationsModel?>(selector: (state) => state.notificationsModelObj, builder: (context, notificationsModelObj) {return ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Padding(padding: EdgeInsets.symmetric(vertical: 7.5.v), child: SizedBox(width: 315.h, child: Divider(height: 1.v, thickness: 1.v, color: appTheme.lightGreen400.withOpacity(0.1))));}, itemCount: notificationsModelObj?.userconnectionItemList.length ?? 0, itemBuilder: (context, index) {UserconnectionItemModel model = notificationsModelObj?.userconnectionItemList[index] ?? UserconnectionItemModel(); return UserconnectionItemWidget(model);});}))])))), Container(height: 69.v, width: double.maxFinite, decoration: BoxDecoration(color: theme.colorScheme.onPrimaryContainer.withOpacity(1))), SizedBox(height: 5.v), Container(height: 69.v, width: double.maxFinite, decoration: BoxDecoration(color: theme.colorScheme.onPrimaryContainer.withOpacity(1)))])))); } 


/// Navigates to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is
/// used to build the navigation stack. When the action is triggered, this
/// function uses the [NavigatorService] to navigate to the previous screen
/// in the navigation stack.
onTapArrowleftone(BuildContext context) { NavigatorService.goBack(); } 
 }
