import 'bloc/legend_bloc.dart';import 'models/legend_model.dart';import 'package:arone_jerome_s_application1/core/app_export.dart';import 'package:arone_jerome_s_application1/presentation/all_friends_page/all_friends_page.dart';import 'package:arone_jerome_s_application1/presentation/discover_page/discover_page.dart';import 'package:arone_jerome_s_application1/presentation/message_main_page/message_main_page.dart';import 'package:arone_jerome_s_application1/presentation/notifications_page/notifications_page.dart';import 'package:arone_jerome_s_application1/widgets/app_bar/appbar_image.dart';import 'package:arone_jerome_s_application1/widgets/app_bar/appbar_image_2.dart';import 'package:arone_jerome_s_application1/widgets/app_bar/appbar_image_3.dart';import 'package:arone_jerome_s_application1/widgets/app_bar/appbar_subtitle_7.dart';import 'package:arone_jerome_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:arone_jerome_s_application1/widgets/custom_bottom_bar.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class LegendScreen extends StatelessWidget {LegendScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

static Widget builder(BuildContext context) { return BlocProvider<LegendBloc>(create: (context) => LegendBloc(LegendState(legendModelObj: LegendModel()))..add(LegendInitialEvent()), child: LegendScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<LegendBloc, LegendState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: CustomAppBar(height: 75.v, leadingWidth: 54.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleft, margin: EdgeInsets.only(left: 44.h, top: 14.v, bottom: 14.v), onTap: () {onTapArrowleftone(context);}), title: AppbarImage2(svgPath: ImageConstant.imgMystylin, margin: EdgeInsets.only(left: 101.h)), actions: [AppbarSubtitle7(text: "lbl_my_style".tr, margin: EdgeInsets.fromLTRB(1.h, 22.v, 18.h, 3.v)), AppbarImage3(svgPath: ImageConstant.imgBookmarkBlack900, margin: EdgeInsets.only(left: 33.h, top: 19.v, right: 18.h)), AppbarSubtitle7(text: "lbl_favorites".tr, margin: EdgeInsets.fromLTRB(7.h, 22.v, 63.h, 3.v))]), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 8.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgPetersoulisbrookehogan12, height: 359.v, width: 280.h, radius: BorderRadius.circular(10.h), alignment: Alignment.center), Padding(padding: EdgeInsets.only(left: 18.h, top: 14.v), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(svgPath: ImageConstant.imgStylepointsicons, height: 11.v, width: 6.h, margin: EdgeInsets.only(bottom: 1.v)), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("lbl_5_000".tr, style: CustomTextStyles.labelMediumRalewayLightgreen400Bold)), Container(height: 2.adaptSize, width: 2.adaptSize, margin: EdgeInsets.only(left: 7.h, top: 4.v, bottom: 7.v), decoration: BoxDecoration(color: appTheme.lightGreen400, borderRadius: BorderRadius.circular(1.h))), Padding(padding: EdgeInsets.only(left: 9.h, bottom: 1.v), child: Text("lbl_legend".tr, style: CustomTextStyles.labelMediumRalewayLightgreen400))])), Padding(padding: EdgeInsets.only(left: 18.h, top: 5.v), child: Text("lbl_olivia_amelie".tr, style: CustomTextStyles.titleLargeRalewayBold)), Padding(padding: EdgeInsets.only(left: 18.h, top: 2.v), child: Text("lbl_stylist".tr, style: CustomTextStyles.labelMediumRalewayGray500)), Container(width: 229.h, margin: EdgeInsets.only(left: 18.h, top: 7.v, right: 67.h), child: Text("msg_i_always_find_beauty".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodySmallLight11_1.copyWith(height: 1.36))), SizedBox(height: 27.v), CustomImageView(svgPath: ImageConstant.imgArrow, height: 1.v, width: 34.h, alignment: Alignment.centerRight), SizedBox(height: 3.v)])), bottomNavigationBar: CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));})));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Dashboard: return AppRoutes.notificationsPage; case BottomBarEnum.Mystylin: return AppRoutes.allFriendsPage; case BottomBarEnum.Upload: return "/"; case BottomBarEnum.Messages: return AppRoutes.messageMainPage; case BottomBarEnum.Discover: return AppRoutes.discoverPage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.notificationsPage: return NotificationsPage.builder(context); case AppRoutes.allFriendsPage: return AllFriendsPage.builder(context); case AppRoutes.messageMainPage: return MessageMainPage.builder(context); case AppRoutes.discoverPage: return DiscoverPage.builder(context); default: return DefaultWidget();} } 


/// Navigates to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is
/// used to build the navigation stack. When the action is triggered, this
/// function uses the [NavigatorService] to navigate to the previous screen
/// in the navigation stack.
onTapArrowleftone(BuildContext context) { NavigatorService.goBack(); } 
 }
