import 'bloc/discover_event_inner_bloc.dart';import 'models/discover_event_inner_model.dart';import 'package:arone_jerome_s_application1/core/app_export.dart';import 'package:arone_jerome_s_application1/widgets/app_bar/appbar_image.dart';import 'package:arone_jerome_s_application1/widgets/app_bar/appbar_subtitle_1.dart';import 'package:arone_jerome_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:arone_jerome_s_application1/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class DiscoverEventInnerScreen extends StatelessWidget {const DiscoverEventInnerScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<DiscoverEventInnerBloc>(create: (context) => DiscoverEventInnerBloc(DiscoverEventInnerState(discoverEventInnerModelObj: DiscoverEventInnerModel()))..add(DiscoverEventInnerInitialEvent()), child: DiscoverEventInnerScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<DiscoverEventInnerBloc, DiscoverEventInnerState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: CustomAppBar(leadingWidth: 51.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleft, margin: EdgeInsets.only(left: 20.h, top: 17.v, bottom: 10.v), onTap: () {onTapArrowleftone(context);}), centerTitle: true, title: AppbarSubtitle1(text: "msg_marissa_walter_fashion2".tr)), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 15.v), child: Column(children: [SizedBox(height: 343.v, width: 315.h, child: Stack(alignment: Alignment.bottomLeft, children: [Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(right: 1.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 278.v, width: 314.h, decoration: AppDecoration.outlineBlack900, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.img2278x314, height: 278.v, width: 314.h, radius: BorderRadius.circular(10.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgImage278x307, height: 278.v, width: 307.h, radius: BorderRadius.circular(10.h), alignment: Alignment.center)])), SizedBox(height: 33.v), Text("msg_december_29_2019".tr, style: CustomTextStyles.labelLargeRobotoBlack900)]))), Align(alignment: Alignment.bottomLeft, child: Text("lbl_chicago_il".tr, style: CustomTextStyles.bodySmallBlack900)), CustomElevatedButton(height: 35.v, width: 121.h, text: "lbl_learn_more".tr, margin: EdgeInsets.only(bottom: 1.v), buttonTextStyle: CustomTextStyles.labelLargeOnPrimaryContainer, alignment: Alignment.bottomRight)])), SizedBox(height: 19.v), SizedBox(width: 314.h, child: Text("msg_witness_the_unvelining".tr, maxLines: 5, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodySmallLight11_1.copyWith(height: 1.33))), SizedBox(height: 5.v)]))));}); } 


/// Navigates to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is
/// used to build the navigation stack. When the action is triggered, this
/// function uses the [NavigatorService] to navigate to the previous screen
/// in the navigation stack.
onTapArrowleftone(BuildContext context) { NavigatorService.goBack(); } 
 }
