import 'bloc/sign_up_three_bloc.dart';import 'models/sign_up_three_model.dart';import 'package:arone_jerome_s_application1/core/app_export.dart';import 'package:arone_jerome_s_application1/widgets/custom_elevated_button.dart';import 'package:arone_jerome_s_application1/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class SignUpThreeScreen extends StatelessWidget {const SignUpThreeScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SignUpThreeBloc>(create: (context) => SignUpThreeBloc(SignUpThreeState(signUpThreeModelObj: SignUpThreeModel()))..add(SignUpThreeInitialEvent()), child: SignUpThreeScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 53.v), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgGs, height: 119.v, width: 123.h), SizedBox(height: 36.v), CustomImageView(svgPath: ImageConstant.imgProgressPrimary, height: 11.v, width: 131.h), SizedBox(height: 21.v), Text("msg_complete_your_profile".tr, style: CustomTextStyles.labelLarge_1), SizedBox(height: 12.v), Text("msg_tell_us_more_about".tr, style: CustomTextStyles.bodySmall11_1), SizedBox(height: 35.v), BlocSelector<SignUpThreeBloc, SignUpThreeState, TextEditingController?>(selector: (state) => state.birthdaylabelController, builder: (context, birthdaylabelController) {return CustomTextFormField(width: 240.h, controller: birthdaylabelController, hintText: "lbl_birthday".tr, hintStyle: CustomTextStyles.bodyMediumBlack900, borderDecoration: TextFormFieldStyleHelper.fillPrimary, fillColor: theme.colorScheme.primary);}), SizedBox(height: 14.v), BlocSelector<SignUpThreeBloc, SignUpThreeState, TextEditingController?>(selector: (state) => state.aboutyoulabelController, builder: (context, aboutyoulabelController) {return CustomTextFormField(width: 240.h, controller: aboutyoulabelController, hintText: "msg_say_something_about".tr, hintStyle: CustomTextStyles.bodyMediumBlack900, textInputAction: TextInputAction.done, borderDecoration: TextFormFieldStyleHelper.fillPrimary, fillColor: theme.colorScheme.primary);}), SizedBox(height: 12.v), SizedBox(height: 32.v, width: 240.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 19.h), child: Text("lbl_favorite_brands".tr, style: CustomTextStyles.bodyMediumBlack900))), Align(alignment: Alignment.center, child: Container(height: 32.v, width: 240.h, decoration: BoxDecoration(color: theme.colorScheme.primary)))])), SizedBox(height: 17.v), CustomElevatedButton(width: 68.h, text: "lbl_submit".tr, onTap: () {onTapSubmit(context);}, alignment: Alignment.centerRight), Spacer(), SizedBox(height: 3.v), GestureDetector(onTap: () {onTapTxtSkipthisstep(context);}, child: Text("lbl_skip_this_step".tr, style: CustomTextStyles.bodySmallLightgreen40011_1))])))); } 
/// Navigates to the signUp4FemaleScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [NavigatorService]
/// to push the named route for the signUp4FemaleScreen.
onTapSubmit(BuildContext context) { NavigatorService.pushNamed(AppRoutes.signUp4FemaleScreen, ); } 
/// Navigates to the dashboardUponLogInScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [NavigatorService]
/// to push the named route for the dashboardUponLogInScreen.
onTapTxtSkipthisstep(BuildContext context) { NavigatorService.pushNamed(AppRoutes.dashboardUponLogInScreen, ); } 
 }
