import 'bloc/more_sidebar_one_bloc.dart';import 'models/more_sidebar_one_model.dart';import 'package:arone_jerome_s_application1/core/app_export.dart';import 'package:arone_jerome_s_application1/widgets/app_bar/appbar_image.dart';import 'package:arone_jerome_s_application1/widgets/app_bar/appbar_subtitle_4.dart';import 'package:arone_jerome_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class MoreSidebarOneScreen extends StatelessWidget {const MoreSidebarOneScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<MoreSidebarOneBloc>(create: (context) => MoreSidebarOneBloc(MoreSidebarOneState(moreSidebarOneModelObj: MoreSidebarOneModel()))..add(MoreSidebarOneInitialEvent()), child: MoreSidebarOneScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<MoreSidebarOneBloc, MoreSidebarOneState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: CustomAppBar(height: 127.v, leadingWidth: 53.h, leading: AppbarImage(svgPath: ImageConstant.imgUser, margin: EdgeInsets.only(left: 36.h, top: 18.v, bottom: 20.v)), title: AppbarSubtitle4(text: "lbl_connections".tr, margin: EdgeInsets.only(left: 26.h))), body: Container(width: 281.h, padding: EdgeInsets.symmetric(horizontal: 32.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [CustomImageView(svgPath: ImageConstant.imgGetstyliniconsblocked, height: 27.adaptSize, width: 27.adaptSize), Padding(padding: EdgeInsets.only(left: 21.h, top: 9.v, bottom: 2.v), child: Text("lbl_block".tr, style: CustomTextStyles.labelLarge12_1))]), SizedBox(height: 15.v), GestureDetector(onTap: () {onTapRowgetstylinico(context);}, child: Row(children: [CustomImageView(svgPath: ImageConstant.imgGetstyliniconsmuted, height: 26.adaptSize, width: 26.adaptSize), Padding(padding: EdgeInsets.only(left: 22.h, top: 5.v, bottom: 5.v), child: Text("lbl_mute".tr, style: CustomTextStyles.labelLarge12))])), SizedBox(height: 5.v)]))));}); } 
/// Navigates to the muteConfirmationScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [NavigatorService]
/// to push the named route for the muteConfirmationScreen.
onTapRowgetstylinico(BuildContext context) { NavigatorService.pushNamed(AppRoutes.muteConfirmationScreen, ); } 
 }
